# Readme:
# postgres username: team4gp
# postgres password: team4pw
# Use http://localhost:9090 to access database 

version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: team4gp
      POSTGRES_PASSWORD: team4pw
    volumes:
      - ./data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
